### ISSUE TITLE
Mobile - Account Icon / Dropdown

### ISSUE THREAD

**Issue by DaveBeirne** [CodyHouse/cd-mega-site-navigation-changelog#2]
Should the Account Icon on mobile be removed from the top nav 
![Screenshot 2020-04-17 at 10 41 31](https://user-images.githubusercontent.com/1081103/79555920-3fae6700-8098-11ea-90de-8e27b55e7d5b.png)

and then be put in the dropdown links included in the navigation like this ?
![Screenshot 2020-04-17 at 10 42 08](https://user-images.githubusercontent.com/1081103/79555932-43da8480-8098-11ea-872b-4ce46b5aa5aa.png)

As the account icon becomes not used in mobile otherwise

**Comment by sebastiano-guerriero** [comment]
Hi Dave,

The account on mobile is a link (e.g., you can use it to link to the login page). If it's not needed, you can remove it and add a new account section/accordion on mobile (that you can then hide on bigger screens using the hide@md util class).

**Comment by DaveBeirne** [comment]
Thanks Sebastiano,

I am just suggesting for functionality / UX  as on desktop it has a dropdown of (account) links and then for mobile these links are no longer in the navigation, so as a mobile user for e.g. after logining in, there is no options to view links of "messages" etc :)

Just an idea

**Comment by sebastiano-guerriero** [comment]
Hi Dave, no prob at all! Any suggestion is welcome :) When I go through the Github issues, I keep my responses short because I try to answer as many issues/questions as possible. Your point makes total sense. 

I don't focus much on the "content meaning" part of the components (i.e., does it make sense to have an account link on the mobile navigation?). I prefer to give all the options instead, even if usually they're not used together (button, icon, icon + label, link, gallery item etc). This way, users can decide for themselves what is needed and what is not, according to their content.  In the specific case of the account icon on mobile, I just wanted to show how a basic icon/link would look like on mobile (the search icon triggers a different action). It could really be any icon though.

Cheers

**Comment by DaveBeirne** [comment]
I understand, Thanks for taking the time  :)
