### ISSUE TITLE
Support for dropdown style of mega-nav__sub-nav

### ISSUE THREAD

**Issue by dean-shanghai** [CodyHouse/cd-mega-site-navigation-changelog#8]
The default 4 layout options are all 100% width style, how to add mega-nav__sub-nav like the dropdown ones in this demo: https://codyhouse.co/ds/components/app/main-header-v2, and with support of "Open navigation on hover".

**Comment by claudia-romano** [comment]
Hi there, we have a [dropdown component](https://codyhouse.co/ds/components/app/dropdown) you can use to create your dropdown menu. 
We have already included an example in the Mega-Site Navigation (you can see it hovering over the user icon on the right of the menu).

There's now a `data-hover` option you can use to open the dropdown on hover (rather than on click). You can find more info here:
https://codyhouse.co/ds/components/info/mega-site-navigation#open-on-hover

Cheers!
